### PR TITLE
docs: add table of content with links to section + code examples

### PR DESCRIPTION
**Pull request by Mayowa-Ojo**
Added a T.O.C for easy navigation seeing that the docs can potentially grow longer. Also added an examples section for further use cases including one example. If the structure is okay with you, I'm ready to work on more examples. 

Share your thoughts. Thanks

### CODE REVIEW

**Comment by solomon-os** [comment]
Resolve conflicts and push

**Comment by solomon-os** [comment]
Also thanks for this man

**Review by solomon-os — APPROVED** [review]
Nice one man thanks.

**Comment by solomon-os** [comment]
Drop your twitter handle we can work on open source stuffs together, I'm cooking up something else

**Comment by Mayowa-Ojo** [comment]
> Drop your twitter handle we can work on open source stuffs together, I'm cooking up something else

Nice. I'm @unorthodev on twitter

**Pull request merged**
